include_recipe cookbook_name + "::base"
include_recipe cookbook_name + "::consul-template"
include_recipe cookbook_name + "::openresty"
include_recipe cookbook_name + "::php"
include_recipe cookbook_name + "::gearman"
include_recipe cookbook_name + "::vault"
