name "jbx"
maintainer "Pablo Canales"
maintainer_email "pablo@jumbleberry.com"
license "All rights reserved"
description "Deploy JBX Application"
long_description "Deploy JBX Application"
version "0.1.0"

depends "configure"
depends "filebeat"
depends "hashicorp-vault"
depends "openresty"
