name "admin"
maintainer "Ian Elliott"
maintainer_email "ian@jumbleberry.com"
license "All rights reserved"
description "Deploy JB Admin Application"
long_description "Deploy JB Admin Application"
version "0.1.1"

depends "configure"
depends "hashicorp-vault"
depends "openresty"
